# Generated by Django 2.2.7 on 2019-11-13 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivilegeDetail',
            fields=[
                ('priv_det_id', models.AutoField(primary_key=True, serialize=False)),
                ('priv_det_date', models.DateField()),
                ('priv_det_level_type', models.CharField(max_length=2)),
                ('priv_det_comt', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivilegeRole',
            fields=[
                ('priv_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('priv_role_seq', models.IntegerField()),
                ('priv_role_comt', models.CharField(max_length=200, null=True)),
                ('priv_role_det_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priv_role_det_id', to='privilege.PrivilegeDetail')),
            ],
            options={
                'unique_together': {('priv_role_seq', 'priv_role_det_id')},
            },
        ),
        migrations.CreateModel(
            name='PrivilegeGrant',
            fields=[
                ('priv_grant_id', models.AutoField(primary_key=True, serialize=False)),
                ('priv_grant_dept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priv_grant_dept_id', to='hr.Department')),
                ('priv_grant_det_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priv_grant_det_id', to='privilege.PrivilegeDetail')),
                ('priv_grant_emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priv_grant_emp_id', to='hr.Employee')),
                ('priv_grant_role_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priv_grant_role_id', to='privilege.PrivilegeRole')),
            ],
        ),
    ]
