# Generated by Django 2.2.7 on 2019-11-13 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=30)),
                ('dept_depen_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_dependency_id', to='hr.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_code', models.CharField(max_length=20, unique=True)),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_phone', models.CharField(max_length=20)),
                ('emp_email', models.CharField(max_length=254)),
                ('emp_message', models.CharField(default='내근 업무 내용을 작성해 주세요.', help_text='내근 업무 내용을 작성해 주세요.', max_length=200)),
                ('emp_annaul', models.CharField(default='0', max_length=2)),
                ('emp_stat', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=1)),
                ('emp_salary', models.IntegerField(default=0)),
                ('emp_vacation_days', models.CharField(default='0', max_length=2)),
                ('emp_type', models.CharField(default='정직원', max_length=2)),
                ('emp_dept_id', models.ForeignKey(default='미정', on_delete=django.db.models.deletion.PROTECT, related_name='emp_dept_id', to='hr.Department')),
                ('emp_mng', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_mng_emp_id', to='hr.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('posit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('posit_name', models.CharField(max_length=30)),
                ('posit_salary', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Punctuality',
            fields=[
                ('punc_id', models.AutoField(primary_key=True, serialize=False)),
                ('punc_date', models.DateField()),
                ('punc_type', models.CharField(max_length=2)),
                ('punc_comt', models.CharField(blank=True, max_length=200, null=True)),
                ('punc_emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punc_emp_id', to='hr.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_posit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emp_posit_id', to='hr.Position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='dept_emp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_emp_id', to='hr.Employee'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attd_id', models.AutoField(primary_key=True, serialize=False)),
                ('attd_date', models.DateField()),
                ('attd_time', models.TimeField()),
                ('attd_type', models.CharField(max_length=2)),
                ('attd_emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attd_emp_id', to='hr.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='PayHistory',
            fields=[
                ('pay_hist_id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_hist_date', models.DateField()),
                ('pay_hist_tot_price', models.BigIntegerField()),
                ('pay_hist_default_price', models.BigIntegerField()),
                ('pay_hist_etc_price', models.BigIntegerField()),
                ('pay_hist_bouns_price', models.BigIntegerField()),
                ('pay_hist_emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_hist_emp_id', to='hr.Employee')),
            ],
            options={
                'unique_together': {('pay_hist_emp_id', 'pay_hist_date')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('emp_hist_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_hist_start_date', models.DateField()),
                ('emp_hist_end_date', models.DateField(default='9999-12-31')),
                ('emp_hist_type', models.CharField(max_length=2)),
                ('emp_hist_comt', models.CharField(blank=True, max_length=200, null=True)),
                ('emp_hist_emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_hist_emp_id', to='hr.Employee')),
            ],
            options={
                'unique_together': {('emp_hist_emp_id', 'emp_hist_start_date', 'emp_hist_end_date')},
            },
        ),
    ]
