# Generated by Django 2.2.7 on 2019-11-13 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('hr', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeDaysManage',
            fields=[
                ('ovt_id', models.AutoField(primary_key=True, serialize=False)),
                ('ovt_date', models.DateField(null=True)),
                ('ovt_start_time', models.TimeField()),
                ('ovt_end_time', models.TimeField()),
                ('ovt_type', models.CharField(max_length=2)),
                ('ovt_comt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('srv_id', models.AutoField(primary_key=True, serialize=False)),
                ('srv_date', models.DateField()),
                ('srv_start_datetime', models.DateTimeField()),
                ('srv_end_datetime', models.DateTimeField()),
                ('srv_finish_date_time', models.DateTimeField()),
                ('srv_location', models.CharField(choices=[('서울', '서울'), ('경기', '경기'), ('기타', '기타')], default='서울', max_length=10)),
                ('srv_directgo', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=1)),
                ('srv_title', models.CharField(help_text='제목을 작성해 주세요.', max_length=200)),
                ('srv_det', models.TextField(help_text='상세 내용을 작성해 주세요.')),
                ('srv_signpath', models.CharField(default='/media/images/signature/nosign.jpg', max_length=254)),
                ('srv_stat', models.CharField(default='N', max_length=1)),
                ('srv_com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srv_com_id', to='client.Company')),
                ('srv_cont_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='srv_cont_id', to='sales.Contract')),
                ('srv_cust_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='srv_cust_id', to='client.Customer')),
                ('srv_emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srv_emp_id', to='hr.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('srv_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('srv_type_name', models.CharField(max_length=30)),
                ('srv_type_comt', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSupportTime',
            fields=[
                ('srv_suptime_id', models.AutoField(primary_key=True, serialize=False)),
                ('srv_suptime_toth', models.FloatField()),
                ('srv_suptime_hour', models.FloatField()),
                ('srv_suptime_ovh', models.FloatField()),
                ('srv_suptime_price', models.BigIntegerField(default=0)),
                ('srv_suptime_emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='srv_suptime_emp_id', to='hr.Employee')),
                ('srv_suptime_pay_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='srv_suptime_pay_date', to='hr.Employee')),
                ('srv_suptime_srv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srv_suptime_srv_id', to='service.ServiceReport', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='servicereport',
            name='srv_srvtype_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='srv_srvtype_id', to='service.ServiceType'),
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('vac_id', models.AutoField(primary_key=True, serialize=False)),
                ('vac_date', models.DateField()),
                ('vac_usetype', models.CharField(max_length=2)),
                ('vac_applytype', models.CharField(max_length=2)),
                ('vac_type', models.CharField(max_length=2)),
                ('vac_emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vac_emp_id', to='hr.Employee')),
            ],
            options={
                'unique_together': {('vac_emp_id', 'vac_date')},
            },
        ),
        migrations.CreateModel(
            name='ServiceWorker',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('worker_emp_name', models.CharField(max_length=30)),
                ('worker_emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_emp_id', to='hr.Employee')),
                ('worker_srv_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_srv_id', to='sales.Contract')),
            ],
            options={
                'unique_together': {('worker_srv_id', 'worker_emp_id')},
            },
        ),
        migrations.CreateModel(
            name='ServiceOvertimeDetail',
            fields=[
                ('ovt_det_id', models.AutoField(primary_key=True, serialize=False)),
                ('ovt_det_comt', models.CharField(max_length=200, null=True)),
                ('ovt_det_ovt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ovt_det_ovt_id', to='service.OvertimeDaysManage')),
                ('ovt_det_srv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ovt_det_srv_id', to='client.Customer')),
            ],
            options={
                'unique_together': {('ovt_det_srv_id', 'ovt_det_ovt_id')},
            },
        ),
    ]
