# Generated by Django 2.2.7 on 2019-11-18 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('hr', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceForm',
            fields=[
                ('srv_form_id', models.AutoField(primary_key=True, serialize=False)),
                ('srv_form_start_datetime', models.DateTimeField()),
                ('srv_form_end_datetime', models.DateTimeField()),
                ('srv_form_location', models.CharField(choices=[('서울', '서울'), ('경기', '경기'), ('기타', '기타')], default='서울', max_length=10)),
                ('srv_form_directgo', models.CharField(choices=[('N', 'N'), ('B', 'B'), ('S', 'S'), ('E', 'E'), ('Y', 'Y')], default='N', max_length=1)),
                ('srv_form_title', models.CharField(help_text='제목을 작성해 주세요.', max_length=200)),
                ('srv_form_det', models.TextField(help_text='상세 내용을 작성해 주세요.')),
                ('srv_form_com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srv_form_com_id', to='client.Company')),
                ('srv_form_emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srv_form_emp_id', to='hr.Employee')),
                ('srv_form_srvtype_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='srv_form_srvtype_id', to='service.ServiceType')),
            ],
        ),
    ]
