# Generated by Django 2.2.7 on 2019-11-13 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cate_id', models.AutoField(primary_key=True, serialize=False)),
                ('cate_comt', models.CharField(max_length=200)),
                ('cate_depen_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cate_dependency_id', to='sales.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SalesIndustryType',
            fields=[
                ('sal_industry_id', models.AutoField(primary_key=True, serialize=False)),
                ('sal_industry_comt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SalesType',
            fields=[
                ('sal_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('sal_type_comt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.BigIntegerField()),
                ('sales1', models.BigIntegerField()),
                ('sales2', models.BigIntegerField()),
                ('sales3', models.BigIntegerField()),
                ('sales4', models.BigIntegerField()),
                ('sales5', models.BigIntegerField()),
                ('sales6', models.BigIntegerField()),
                ('sales7', models.BigIntegerField()),
                ('sales8', models.BigIntegerField()),
                ('sales9', models.BigIntegerField()),
                ('sales10', models.BigIntegerField()),
                ('sales11', models.BigIntegerField()),
                ('sales12', models.BigIntegerField()),
                ('salesq1', models.BigIntegerField()),
                ('salesq2', models.BigIntegerField()),
                ('salesq3', models.BigIntegerField()),
                ('salesq4', models.BigIntegerField()),
                ('profit1', models.BigIntegerField()),
                ('profit2', models.BigIntegerField()),
                ('profit3', models.BigIntegerField()),
                ('profit4', models.BigIntegerField()),
                ('profit5', models.BigIntegerField()),
                ('profit6', models.BigIntegerField()),
                ('profit7', models.BigIntegerField()),
                ('profit8', models.BigIntegerField()),
                ('profit9', models.BigIntegerField()),
                ('profit10', models.BigIntegerField()),
                ('profit11', models.BigIntegerField()),
                ('profit12', models.BigIntegerField()),
                ('profitq1', models.BigIntegerField()),
                ('profitq2', models.BigIntegerField()),
                ('profitq3', models.BigIntegerField()),
                ('profitq4', models.BigIntegerField()),
                ('year_sales_sum', models.BigIntegerField()),
                ('year_profit_sum', models.BigIntegerField()),
                ('goal_dept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal_dept_id', to='hr.Department')),
                ('goal_emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal_emp_id', to='hr.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('cont_id', models.AutoField(primary_key=True, serialize=False)),
                ('cont_code', models.CharField(max_length=30)),
                ('cont_name', models.CharField(max_length=200)),
                ('cont_emp_name', models.CharField(max_length=30)),
                ('cont_emp_dept_name', models.CharField(max_length=30)),
                ('cont_cate_main', models.CharField(max_length=200)),
                ('cont_cate_sub', models.CharField(max_length=200)),
                ('cont_date', models.DateField()),
                ('cont_step', models.CharField(choices=[('Opportunity', 'Opportunity'), ('Firm', 'Firm'), ('Drop', 'Drop')], default='Opportunity', max_length=20)),
                ('cont_start_date', models.DateField(blank=True, null=True)),
                ('cont_end_date', models.DateField(blank=True, null=True)),
                ('cont_depo_con', models.CharField(blank=True, choices=[('계산서 발행 후', '계산서 발행 후'), ('당월', '당월'), ('익월', '익월'), ('당월 말', '당월 말'), ('익월 초', '익월 초'), ('익월 말', '익월 말')], default='계산서 발행 후', max_length=20, null=True)),
                ('cont_depo_con_day', models.IntegerField(blank=True, default=0, null=True)),
                ('cont_paper', models.FileField(blank=True, null=True, upload_to='contractPaper/%Y_%m')),
                ('cont_order_paper', models.FileField(blank=True, null=True, upload_to='orderPaper/%Y_%m')),
                ('cont_comt', models.CharField(blank=True, max_length=200, null=True)),
                ('cont_modify_order_paper', models.CharField(blank=True, choices=[('N', 'N'), ('Y', 'Y')], default='N', max_length=1, null=True)),
                ('newCompany', models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='N', max_length=10)),
                ('cont_sal_industry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont_sal_industry_id', to='sales.SalesIndustryType')),
                ('cont_sal_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont_sal_type_id', to='sales.SalesType')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('reve_id', models.AutoField(primary_key=True, serialize=False)),
                ('reve_seq', models.SmallIntegerField()),
                ('reve_price', models.BigIntegerField()),
                ('reve_profit_price', models.BigIntegerField()),
                ('reve_profit_ratio', models.FloatField()),
                ('reve_pred_billing_date', models.DateField(blank=True, null=True)),
                ('reve_billing_date', models.DateField(blank=True, null=True)),
                ('reve_pred_depo_date', models.DateField(blank=True, null=True)),
                ('reve_depo_date', models.DateField(blank=True, null=True)),
                ('reve_stat', models.CharField(default='N', max_length=1, null=True)),
                ('reve_comt', models.CharField(blank=True, max_length=200, null=True)),
                ('reve_com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reve_com_id', to='client.Company')),
                ('reve_cont_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reve_cont_id', to='sales.Contract')),
                ('reve_emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reve_emp_id', to='sales.Contract')),
            ],
            options={
                'unique_together': {('reve_cont_id', 'reve_emp_id', 'reve_seq')},
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purc_id', models.AutoField(primary_key=True, serialize=False)),
                ('purc_seq', models.SmallIntegerField()),
                ('purc_price', models.BigIntegerField()),
                ('purc_pred_billing_date', models.DateField(blank=True, null=True)),
                ('purc_billing_date', models.DateField(blank=True, null=True)),
                ('purc_pred_withdraw_date', models.DateField(blank=True, null=True)),
                ('purc_withdraw_date', models.DateField(blank=True, null=True)),
                ('purc_stat', models.CharField(default='N', max_length=1, null=True)),
                ('purc_comt', models.CharField(blank=True, max_length=200, null=True)),
                ('purc_com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purc_com_id', to='client.Company')),
                ('purc_cont_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purc_cont_id', to='sales.Contract')),
                ('purc_emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purc_emp_id', to='sales.Contract')),
            ],
            options={
                'unique_together': {('purc_cont_id', 'purc_emp_id', 'purc_seq')},
            },
        ),
        migrations.CreateModel(
            name='ContractManager',
            fields=[
                ('cont_mng_id', models.AutoField(primary_key=True, serialize=False)),
                ('cont_mng_date', models.DateField()),
                ('cont_mng_sal_price', models.BigIntegerField()),
                ('cont_mng_profit_price', models.BigIntegerField()),
                ('cont_mng_profit_ratio', models.FloatField()),
                ('cont_mng_cont_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont_mng_cont_id', to='sales.Contract')),
                ('cont_mng_cust_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cont_mng_cust_id', to='client.Customer')),
                ('cont_mng_emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont_mng_emp_id', to='hr.Employee')),
            ],
            options={
                'unique_together': {('cont_mng_cont_id', 'cont_mng_emp_id')},
            },
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('cont_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('cont_item_seq', models.SmallIntegerField()),
                ('cont_item_comt', models.CharField(max_length=200)),
                ('cont_item_num', models.SmallIntegerField()),
                ('cont_item_price', models.BigIntegerField()),
                ('cont_item_cate_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cont_item_cate_id', to='sales.Category')),
                ('cont_item_cont_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont_item_cont_id', to='sales.Contract')),
            ],
            options={
                'unique_together': {('cont_item_cont_id', 'cont_item_cate_id', 'cont_item_seq')},
            },
        ),
    ]
